[package]
name = "crash-context"
description = "Provides types containing target specific contextual information during an exception"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
cfg-if = "1.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
