[workspace]
members = [
    "crash-context",
    "exception-handler",
    "minidumper",
    "minidumper-test",
    "sadness-generator",
]

[profile.dev]
debug = 2

[patch.crates-io]
minidump = { git = "https://github.com/EmbarkStudios/rust-minidump", branch = "master" }
minidump-common = { git = "https://github.com/EmbarkStudios/rust-minidump", branch = "master" }
