[package]
name = "exception-handler"
description = "Allows running of user code during exceptional events"
repository = "https://github.com/EmbarkStudios/crash-handling"
version = "0.0.1"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/exception-handler"
homepage = "https://github.com/EmbarkStudios/crash-handling/tree/main/exception-handler"
keywords = ["breakpad", "minidump", "crash", "signal", "exception"]
