[package]
name = "minidumper"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
log = "0.4"
thiserror = "1.0"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
# Minidump writing for linux
#minidump_writer_linux = { git = "https://github.com/EmbarkStudios/minidump_writer_linux", branch = "changes" }
minidump_writer_linux = { path = "../../minidump_writer_linux" }
# Event loop for uds
mio = "0.7"
# Improved Unix domain socket support, includes features that are not available in std
uds = { version = "0.2.6", features = ["mio_07"] }

[target.'cfg(target_os = "windows")'.dependencies]
# Named pipe support, though Windows 10+ does support Unix domain sockets
named_pipe = "0.4"

[dev-dependencies]
# catching crashes to request minidumps
exception-handler = { path = "../exception-handler" }
# uuid generation
uuid = { version = "0.8", features = ["v4"] }
backtrace = "0.3"